### ISSUE TITLE
Deprecated Version of the Request Package 

### ISSUE THREAD

**Issue by bdsoha** [mancioshell/node-risco-client#1]
Unfortunately, the `request` dependency you are using has been officially deprecated.

https://medium.com/better-programming/request-has-been-deprecated-a76415b4910b 

It seems like you should look for a replacement.

**Comment by bdsoha** [comment]
@mancioshell Swapping out `request` with `axios` is a simple refactor, I would be willing to contribute.
I just want to make sure that this is something you are interested in supporting.

**Comment by mancioshell** [comment]
@bdsoha sorry for the delay. I have just updated all legacy dependencies.
